swagger: "2.0"
info:
  description: "This is the canary app. Its purpose is just to sit on a server and look pretty."
  version: "1.0.0"
  title: "Canary"
basePath: "/canary"
tags:
- name: "main"
  description: "Main service"
- name: "health"
  description: "Health checks"
schemes:
- "https"
paths:
  /:
    get:
      tags:
      - "main"
      summary: "Get an insightful quote"
      description: "Quotes can be a userful source of wisdom."
      operationId: "getQuote"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Quote"
  /health/alive:
    get:
      tags:
      - "health"
      summary: "Determine if app is alive"
      description: "App should be considered alive if and only if response code is 200 and the 'alive' attribute in the response is set to true."
      operationId: "getAlive"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Alive"
  /health/ready:
    get:
      tags:
      - "health"
      summary: "Determine if app is ready to serve requests"
      description: "App should be considered ready if and only if response code is 200 and the 'ready' attribute in the response is set to true."
      operationId: "getReady"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Ready"
definitions:
  Quote:
    type: "object"
    properties:
      quote:
        type: "string"
        description: "Something somebody has said or written at some point in time"
      author:
        type: "string"
        description: "The person who said or wrote this particular nugget of wisdom"
  Alive:
    type: "object"
    properties:
      alive:
        type: boolean
        description: "True if service is currently alive, false if it is dead"
  Ready:
    type: "object"
    properties:
      ready:
        type: boolean
        description: "True if service is currently ready to serve requests, false if it is not"

        